# JVM heap para el daemon Gradle. Aumentar si el build se traba.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# AndroidX (obligatorio en proyectos modernos).
android.useAndroidX=true

# Kotlin code style.
kotlin.code.style=official

# Permite que las clases R no se compartan entre modulos (mas rapido).
android.nonTransitiveRClass=true
